### PR TITLE
Feature audio buttons

### LINKED ISSUE #128: Pause button stays disabled after reviving
The pause button stays disabled after reviving once.

### PR DESCRIPTION
**Pull request by Taeir**
- Added eating sound
- Added button click sounds
- Added mute toggle button during the game.
- Fixed #128 

<feature,bug

### CODE REVIEW

**Comment by ChielBruin** [comment]
It looks good, but the build fails.
Fix that first
<review

**Comment by jessearens** [comment]
I think it's best if you turn src/main/resources/sound/effects/button2.wav into an .mp3 format. In my opinion it's best if all music/soundeffects run from the same format.

Other code seems fine, so if the build passes and you change the aforementioned suggestion it's good for me.

<organisation,feature

**Comment by Taeir** [comment]
@jessearens I removed the sound effect since it was unused.

<organisation,feature

**Comment by jessearens** [comment]
In that case, good to merge!

<feature

**Pull request merged**
