### PR TITLE
Feature achievements

### PR DESCRIPTION
**Pull request by jessearens**
This pull request adds some documentation on how the actual achievements will be implemented next sprint. 
<feature,organisation,documentation

### CODE REVIEW

**Comment by LMiljak** [comment]
:+1: 
<feature,organisation,documentation

**Comment by Diocruel** [comment]
Please do not upload astah.lock files. Either add them to the gitignore or make sure it does not exist when commiting! 

Upload another commit without the lock file.

<feature,organisation,documentation

**Comment by Diocruel** [comment]
Good job on the rest though! :+1:

**Comment by jessearens** [comment]
Removed the astah.lock file.
<organisation

**Comment by LMiljak** [comment]
I'm merging it then.

<review

**Pull request merged**
