### PR TITLE
Feature multiplayer screen

### PR DESCRIPTION
**Pull request by Diocruel**
Implemented multiplayer screen for use in the multiplayer assignment of the TA.

<feature, user-interface

### CODE REVIEW

**Comment by Diocruel** [comment]
Build failed on weird error, investigating.

<review, bug

**Comment by Diocruel** [comment]
Build passed, so please review.

<review

**Comment by LMiljak** [comment]
Nice job, you got the hang of Javafx pretty quickly 
:+1: 

<feature, user-interface

**Comment by Taeir** [comment]
Looks good, and also seems to work nicely with the new scaling implemented by @ChielBruin.

<feature, user-interface

**Pull request merged**
