### PR TITLE
Changed a few hours because of a misjudgement.

### PR DESCRIPTION
**Pull request by Diocruel**
This should better reflect @jessearens hours
<documentation

### CODE REVIEW

**Comment by Taeir** [comment]
Just some updates in hours, good to merge after build passes.

<documentation

**Comment by jessearens** [comment]
I said 20 hours, now you turned it into 14?

<bug

**Comment by MrCrime** [comment]
My absolute sincere apology for merging the last time. I feel so sorry.
(It looks good though).

<documentation

**Comment by MrCrime** [comment]
Never mind. Poor Jesse.

**Comment by Diocruel** [comment]
So Next time don't try to close pull request anymore.... It's better when it stays up so other people can comment on it too!

I read it as 20 hours total, Calm down your horses.

<review, documentation

**Comment by jessearens** [comment]
Sorry, didn't realize it had to stay open.

It wasn't meant angry or anything either. Thanks for updating it!

<documentation,review

**Comment by Diocruel** [comment]
Np, this is the reason we do pull request reviewing after all. Merged

<review

**Pull request merged**
