### PR TITLE
Add sprint plan #5.

### PR DESCRIPTION
**Pull request by jessearens**
<documentation

### CODE REVIEW

**Comment by ChielBruin** [comment]
Looks good!
<documentation

**Comment by LMiljak** [comment]
I disagree a little bit with the sprint plan (the boss part), I'm currently working on subtasks of the boss feature. Patience plz.

<documentation

**Comment by LMiljak** [comment]
Nevermind, I just made it worse. I'm merging it

<documentation

**Comment by ChielBruin** [comment]
:-)
<documentation

**Pull request merged**
