### PR TITLE
Add requirements for Sprint 5 to repository.

### PR DESCRIPTION
**Pull request by jessearens**
<thereisnoappropriatetagforthistypeofcommitisthere?

### CODE REVIEW

**Comment by ChielBruin** [comment]
@jessearens <documentation
<review

**Comment by ChielBruin** [comment]
It looks good, especially nice that you made the changes in italic!

<documentation

**Comment by jessearens** [comment]
I disagree that the tag should be <documentation:
"documentation - the comment or commit is related to documentation in the code, most likely a code comment (such as javadoc)" - octopull.rmhartog.me
This is not documentation in or of the code.

<review,stilldontknowtherighttag

**Comment by LMiljak** [comment]
I think it should be documentation though, just pick the tag that looks most like it if you're not sure.
I'm merging this.

<documentation

**Pull request merged**
