### PR TITLE
Achievements observerstructure

### PR DESCRIPTION
**Pull request by jessearens**
I want to merge this into the main feature_achievements branch. As I'll be working with the observer pattern as coded into this pull request, I would like some reviews before continuing with the implementation of the rest of achievements.

P.S.: quite a big part of the code lines was merging the master branch into this branch which was already approved, so make sure you don't waste too much time on these changes. Also do not be scared off by the amount of lines changed as most of these lines again have been approved already. I would suggest you look at the last few commits: d81b6e1,  0ae7fee, b1627cf and 4c20386.

<feature,review

### CODE REVIEW

**Comment by Diocruel** [comment]
Seems fine, don't forget to write tests though. +1

<testing

**Comment by jessearens** [comment]
Of course not! Just wanted approval of this before continuing on tests and further implementation.

<testing

**Comment by ChielBruin** [comment]
Achievement get: Achievements!
good job, but try to minimize the number of included commits
<feature

**Comment by jessearens** [comment]
You are right. I do not know where it went wrong, but will be extra careful the next time.

**Pull request merged**
