### PR TITLE
Preload screens and images

### PR DESCRIPTION
**Pull request by Taeir**
Also fixes screen flickering on transitions.

### CODE REVIEW

**Comment by Diocruel** [comment]
Merging fun

**Comment by ChielBruin** [comment]
It seems good, but is unable to merge into the master..
Looks to me it needs to be closed and reopened after this is fixed

**Comment by Taeir** [comment]
I can merge it from the console, so that is no problem.

**Comment by Diocruel** [comment]
I have looked over the New code too. Looks good! Should fix the splashsceen

**Comment by jessearens** [comment]
Looks good for me. Good luck merging it.

**Pull request merged**
