### PR TITLE
Final UML

### PR DESCRIPTION
**Pull request by ChielBruin**
Updated the UML to the final version.
This version includes all the classes and methods that are present at the master after merging pull request #224.
Just look at  'Class Diagram.png'
<documentation

### CODE REVIEW

**Comment by LMiljak** [comment]
The FreezePowerUp extends PowerUpDuration, not PowerUp.

<documentation, bug

**Comment by jessearens** [comment]
The document seems to be correct with exception to Luka's comment.
Right now you place the document in a folder with a lot of other documents. Perhaps it's name should be more clear or the other documents should be put into a subfolder in order to make it more clear that this is the final UML class diagramme of the whole game?

<organisation,documentation

**Comment by ChielBruin** [comment]
Thanks @jessearens  for the suggestion and @MrCrime  for spotting the mistake in one of the relations!
They are fixed now.

<documentation, organisation, review

**Comment by LMiljak** [comment]
Good job!
Merging

<documentation

**Pull request merged**
