### PR TITLE
Improve naming of powerups.

### PR DESCRIPTION
**Pull request by jessearens**
Should be more clear now.

<naming

### CODE REVIEW

**Comment by LMiljak** [comment]
I would have liked for the names of PowerUps to start with "PowerUp" instead of ending with it, so that they're all grouped together in an alphabetic order. Now the superclasses PowerUp and DurationPowerUp are mixed up with them. But I guess this will have to do.

<naming

**Comment by jessearens** [comment]
The superclass DurationPowerUp is now called PowerUpDuration and so it should still be somewhat seperated from the other classes. This type of naming better resembles English grammar than the other way around.

<naming

**Comment by Diocruel** [comment]
I agree with Jesse, the meaning of the classes is more important than the position in the list. Though there might be a way to do both. The branch has conflicts that must be resolved before merging, can do this tomorrow if no one else wants to, in the break.

<naming

**Comment by jessearens** [comment]
Simplest merge conflict to fix. All that had to be done what merging master into the branch, nothing else :). As Luka and Robin both already reacted positively to this request, I'm merging it.

<naming

**Pull request merged**
