### PR TITLE
Added sound settings

### PR DESCRIPTION
**Pull request by ChielBruin**
Added sound setings and made it mergable with master.
I also implemented that the screen is resized when this setting is changed.
take a look at the settings, Fish.io and settingScreenController class.

<feature

### CODE REVIEW

**Comment by jessearens** [comment]
Could you do a merge from master into the branch you want to merge into first so that both branches contain the master changes? That way all the pull request changes don't get cluttered up with these other changes. I cannot really work out what to look at this way.

<review

**Comment by ChielBruin** [comment]
That would not work, I have to merge the master into this branch to be able to create a merge-able pull request.
The files that you want to take a look at are the following:
- Settings
- Fish.IO
- ScreenController

or you could take a look at the following commits:
- ffd4e38
- fa02518
- 6b9bf54
- 8c6c4fb

**Comment by jessearens** [comment]
Okay, thanks for the clarification on what to look into. Looks good to me! 

<feature

**Comment by Taeir** [comment]
I'm not so keen on moving the volumes to the settings class. You are making the settings class more into a data class than it already is, and making Audio Engine more of a god class by having it access more external data.

<feature

**Comment by Taeir** [comment]
Changed interaction to something I think we will both like. Sliders are stored in settings, but are not requested every time.

<organisation

**Pull request merged**
