### PR TITLE
Added images for indicating achievement levels.

### PR DESCRIPTION
**Pull request by Diocruel**
Wohooo, more sprites!

<feature

### CODE REVIEW

**Comment by LMiljak** [comment]
:+1: 
This was extremely difficult to review, consider smaller pull requests.

<review

**Comment by Diocruel** [comment]
0/0 lines added/deleted are the worst pull request! I know right!?

<socializing

**Comment by jessearens** [comment]
The pull request looks great!

However, if you decide to use a new tag, you should also inform mr Hartog that he has to add it to his new list of tags for octopull.

<feature,review,socializing

**Comment by Diocruel** [comment]
He should use Generic tags!

**Pull request merged**
