### PR TITLE
made FishIO final

### PR DESCRIPTION
**Pull request by LMiljak**
It was already a sort of a singleton class, now it's officially a
singleton class.

<organisation

### CODE REVIEW

**Comment by Diocruel** [comment]
Can you explain why this is necessary though? Making a class final is not something that instantly makes it a singleton :P

<review

**Comment by Taeir** [comment]
Yeah, thats okay :P

<organisation

**Comment by Taeir** [comment]
@Diocruel It is a singleton class. The getInstance() is somewhat proof of that. There is only one FishIO instance at any point in time, since our program runs only one javafx Application.

Making a class final makes it impossible to be extended. A singleton is a static entity, and thus not to be extended. Therefore, making it a final class makes perfect sense.

<review

**Comment by Diocruel** [comment]
Okay thanks!

<review

**Pull request merged**
