### PR TITLE
Created UML diagram for Logger ex 2.2b

### PR DESCRIPTION
**Pull request by Diocruel**
<documentation

### CODE REVIEW

**Comment by Taeir** [comment]
Apart from one mistake in the multiplicity for Log with IHandler, it looks good. (The multiplicity should be \* instead of 1..*, since a Logger can have no Handlers).

<documentation

**Comment by Diocruel** [comment]
Will close pull request for now! I agree

<documentation

**Comment by Diocruel** [comment]
Fixed!

<documentation

**Comment by ChielBruin** [comment]
TimestampFormat and TxtFileHandler seem to be swapped.

<documentation

**Comment by Diocruel** [comment]
Fixed both suggestions, merging. Thanks!

<review, bug

**Pull request merged**
